package com.cd.entity;

import java.time.LocalDateTime;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedEnum;
import com.cd.dto.LogLevel;
import com.cd.util.DateTimeConverter;

@DynamoDBTable(tableName = "log")
public class Log {
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String uuid;
	
	@DynamoDBAttribute
	@DynamoDBTypeConverted(converter = DateTimeConverter.class)
	private LocalDateTime timestamp;
	
	@DynamoDBAttribute
	@DynamoDBTypeConvertedEnum
	private LogLevel level;
	
	@DynamoDBAttribute
	private String message;

	public Log() {
		super();
	}

	public Log(LocalDateTime timestamp, LogLevel level, String message) {
		super();
		this.timestamp = timestamp;
		this.level = level;
		this.message = message;
	}

	public String getUuid() {
		return uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	public LocalDateTime getTimestamp() {
		return timestamp;
	}

	public void setTimestamp(LocalDateTime timestamp) {
		this.timestamp = timestamp;
	}

	public LogLevel getLevel() {
		return level;
	}

	public void setLevel(LogLevel level) {
		this.level = level;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}
}
